# Generated by Django 3.2.9 on 2021-11-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=120, verbose_name='Symbol Name')),
                ('trade_date', models.DateTimeField(verbose_name='Trade Date')),
                ('order_id', models.IntegerField(verbose_name='Order ID')),
                ('status', models.CharField(max_length=120, verbose_name='Status')),
                ('bid_price', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Bid Price')),
                ('ask_price', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Ask Price')),
                ('side', models.CharField(max_length=120, verbose_name='Side')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantity')),
                ('tif', models.CharField(max_length=120, verbose_name='Time in Force')),
                ('order_price', models.IntegerField(verbose_name='Order Price')),
            ],
        ),
    ]
